name: laundry_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  # firebase_core: ^3.10.0
  # firebase_auth: ^5.4.0
  # cloud_firestore: ^5.6.0
  # firebase_storage: ^12.4.0
  image_picker: ^1.1.2
  mobile_scanner: ^5.1.0
  vibration: ^2.0.1
  audioplayers: ^5.2.1
  qr_flutter: ^4.1.0
  geolocator: ^14.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_ringtone_player: ^4.0.0+4
  webview_flutter: ^4.13.1
  geocoding: ^4.0.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # --- PINDAH KESINI: Tool untuk generate icon ---
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  # Jika nanti ingin menampilkan gambar logo di dalam aplikasi (misal di halaman login),
  # hapus tanda pagar (#) di bawah ini dan sesuaikan nama foldernya:
  # assets:
  #   - assets/

# --- KONFIGURASI ICON APLIKASI ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"