// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1QJ4KgSbdGbzZrQ70PaeNX1_Sgov-vSo',
    appId: '1:1068769197385:web:ed3571bab3d6707846ee98',
    messagingSenderId: '1068769197385',
    projectId: 'laundryapp-f9d0d',
    authDomain: 'laundryapp-f9d0d.firebaseapp.com',
    storageBucket: 'laundryapp-f9d0d.firebasestorage.app',
    measurementId: 'G-12270WEZR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXHFuTO1KcWoWyBBQB5WeiOE6Uqjmltt4',
    appId: '1:1068769197385:android:00739d6644de58be46ee98',
    messagingSenderId: '1068769197385',
    projectId: 'laundryapp-f9d0d',
    storageBucket: 'laundryapp-f9d0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGCSXNzme3qKs33omDuBrWt5kDNbsZFlU',
    appId: '1:1068769197385:ios:f3acef671dd4dbdc46ee98',
    messagingSenderId: '1068769197385',
    projectId: 'laundryapp-f9d0d',
    storageBucket: 'laundryapp-f9d0d.firebasestorage.app',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGCSXNzme3qKs33omDuBrWt5kDNbsZFlU',
    appId: '1:1068769197385:ios:f3acef671dd4dbdc46ee98',
    messagingSenderId: '1068769197385',
    projectId: 'laundryapp-f9d0d',
    storageBucket: 'laundryapp-f9d0d.firebasestorage.app',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1QJ4KgSbdGbzZrQ70PaeNX1_Sgov-vSo',
    appId: '1:1068769197385:web:e50dc5cf698d125046ee98',
    messagingSenderId: '1068769197385',
    projectId: 'laundryapp-f9d0d',
    authDomain: 'laundryapp-f9d0d.firebaseapp.com',
    storageBucket: 'laundryapp-f9d0d.firebasestorage.app',
    measurementId: 'G-QQSQZY65W2',
  );
}
